/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

     

/**
 *
 * @author Albin Malmquist
 */
public class AdminKontrollPanelAvdelning extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminKontrollPanelAvdelning.class.getName());

    /**
     * Creates new form AdminKontrollPanelAvdelning
     * @param idb
     */
    public AdminKontrollPanelAvdelning(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKontrollPanel = new javax.swing.JLabel();
        btnRedigeraBefintligAvd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKontrollPanel.setText("Kontroll panel för avdelningar");

        btnRedigeraBefintligAvd.setText("Redigera befintlig avdelning");
        btnRedigeraBefintligAvd.addActionListener(this::btnRedigeraBefintligAvdActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRedigeraBefintligAvd, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKontrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKontrollPanel)
                .addGap(34, 34, 34)
                .addComponent(btnRedigeraBefintligAvd)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedigeraBefintligAvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraBefintligAvdActionPerformed
        // TODO add your handling code here:
       try {
           
           AvdelningSQL avdSQL = new AvdelningSQL(idb);
           var avdelningar = avdSQL.hamtaAllaAvdelningar();
           
           String [] lista = new String[avdelningar.size()];
           for (int i = 0; i < avdelningar.size(); i++) {
               var rad = avdelningar.get(i);
               lista[i] = rad.get("avdid") + " - " + rad.get("namn");
           }
           
           String val = (String) JOptionPane.showInputDialog(
                   this,"Välj avdelning att redigera: ", "Redigera avdelning",
                   JOptionPane.QUESTION_MESSAGE, null, lista, lista[0]);
           if (val != null) {
               int avdid = Integer.parseInt(val.split(" - ")[0]);
               new RedigeraAvdelning(idb, avdid).setVisible(true);
           }
          
           } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Kunde inte hämta avdelningar: " + e.getMessage());
           }
                
        
        
        
    }//GEN-LAST:event_btnRedigeraBefintligAvdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new AdminKontrollPanelAvdelning().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraBefintligAvd;
    private javax.swing.JLabel lblKontrollPanel;
    // End of variables declaration//GEN-END:variables

}
