/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 * en jFrame klass som ger användare en överblick över deras avdelning.
 * Finns även en sökfunktion för att hitta specifika handläggare. 
 */
public class AvdelningJframe extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvdelningJframe.class.getName());

    /**
     * Creates new form AvdelningJframe
     */
    public AvdelningJframe(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        tblVisaAnstallda.setVisible(true);

        fyllAvdelningsInfo();
        visaAvdAnstallda();
    }

    private void fyllAvdelningsInfo() {
        try {
            String sql = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            String avdidString = idb.fetchSingle(sql);
            int avdid = Integer.parseInt(avdidString);

            AvdelningSQL avdSQL = new AvdelningSQL(idb);
            Avdelning avd = avdSQL.hamtaAvdelningMedId(avdid);

            lblAvdid.setText("AVDid: " + String.valueOf(avd.getAvdid()));
            lblAvdNamn.setText(avd.getNamn());
            lblAvdAdress.setText("Adress: " + avd.getAdress());
            lblAvdStad.setText("Stad: " + avd.getStad());
            lblAvdEpost.setText("Epost: " + avd.getEpost());
            lblAvdTelefon.setText("TelNr: " + avd.getTelefon());
            lblAvdChef.setText("Chef: " + avd.getChef());
            lblAvdBeskrivning.setText("Beskrivning: " + avd.getBeskrivning());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void visaAvdAnstallda() { // visar alla anstallda (samt deras info) på avdelningen i en tabell.
        try {
            String sql = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            String avdidString = idb.fetchSingle(sql);
            int avdid = Integer.parseInt (idb.fetchSingle(sql));
            
            AvdelningSQL avdSQL = new AvdelningSQL(idb);
            var visaAnstallda = avdSQL.getPersonalForAvdelning(avdid);
            
            DefaultTableModel modell = (DefaultTableModel) tblVisaAnstallda.getModel();
            modell.setRowCount(0);
            
            for (var person : visaAnstallda) {
                 modell.addRow(new Object[]{
                     person.get("aid"), person.get("fornamn"), person.get("efternamn"), person.get("epost"), person.get("telefon")});
            }
                 tblVisaAnstallda.setVisible(!visaAnstallda.isEmpty());
           
            } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Anstallda från avdelningen kunde inte hämtas.");
            }
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
            
            
           
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lblAvdEpost1 = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        txtSokHandlaggare = new javax.swing.JTextField();
        lblSokHandlaggare = new javax.swing.JLabel();
        lblAvdid = new javax.swing.JLabel();
        lblAvdNamn = new javax.swing.JLabel();
        lblAvdAdress = new javax.swing.JLabel();
        lblAvdStad = new javax.swing.JLabel();
        lblAvdEpost = new javax.swing.JLabel();
        lblAvdTelefon = new javax.swing.JLabel();
        lblAvdChef = new javax.swing.JLabel();
        lblAvdBeskrivning = new javax.swing.JLabel();
        btnSokHandlaggare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisaAnstallda = new javax.swing.JTable();
        btnRedigeraAvdelning = new javax.swing.JButton();
        lblAvdAnstallda = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        lblAvdEpost1.setText("epost");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAvdelning.setText("Avdelning:");

        lblSokHandlaggare.setText("Sök efter handläggare:");

        lblAvdid.setText("avdid");

        lblAvdNamn.setText("namn");

        lblAvdAdress.setText("adress");

        lblAvdStad.setText("stad");

        lblAvdEpost.setText("epost");

        lblAvdTelefon.setText("telefon");

        lblAvdChef.setText("chef");

        lblAvdBeskrivning.setText("beskrivning");

        btnSokHandlaggare.setText("Sök");
        btnSokHandlaggare.addActionListener(this::btnSokHandlaggareActionPerformed);

        tblVisaAnstallda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "aid", "fornamn", "efternamn", "epost", "telefon"
            }
        ));
        jScrollPane1.setViewportView(tblVisaAnstallda);

        btnRedigeraAvdelning.setText("Redigera avdelning");
        btnRedigeraAvdelning.addActionListener(this::btnRedigeraAvdelningActionPerformed);

        lblAvdAnstallda.setText("Anställda på avdelningen:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvdNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSokHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSokHandlaggare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSokHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRedigeraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvdAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(lblAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblAvdAnstallda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSokHandlaggare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSokHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSokHandlaggare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRedigeraAvdelning))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTillbaka)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokHandlaggareActionPerformed
        /* när en användare trycker på knappen ändras visaAnstallda tabellen till att endast 
           visa handläggare vars namn (eller epost) matchar det användaren skrev in i sökrutan.
        */
                String sokterm = txtSokHandlaggare.getText();
        try {
            String sql = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            int avdid = Integer.parseInt(idb.fetchSingle(sql));
            
            AvdelningSQL avdSQL = new AvdelningSQL(idb); 
            var sokResultat = avdSQL.sokHandlaggare(avdid, sokterm);
            
             DefaultTableModel modell = (DefaultTableModel) tblVisaAnstallda.getModel();
             modell.setRowCount(0);
             
             for (var person : sokResultat) {
                 modell.addRow(new Object[]{
                     person.get("aid"), person.get("fornamn"), person.get("efternamn"), person.get("epost"), person.get("telefon")});
             }
            tblVisaAnstallda.setVisible(!sokResultat.isEmpty());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSokHandlaggareActionPerformed

    private void btnRedigeraAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraAvdelningActionPerformed
        //Endast admin har behörigheten att ändra avdelningar, här kontrolleras det att den inloggade användaren är en admin.
        if (ValAvRoll.arAdmin(idb, inloggadAnvandare)){
        new AdminKontrollPanelAvdelning(idb).setVisible(true);
        } else {
        JOptionPane.showMessageDialog(this, "Endast administratörer har behörigheten att redigera avdelningar.");
        }
    }//GEN-LAST:event_btnRedigeraAvdelningActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraAvdelning;
    private javax.swing.JButton btnSokHandlaggare;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAvdAdress;
    private javax.swing.JLabel lblAvdAnstallda;
    private javax.swing.JLabel lblAvdBeskrivning;
    private javax.swing.JLabel lblAvdChef;
    private javax.swing.JLabel lblAvdEpost;
    private javax.swing.JLabel lblAvdEpost1;
    private javax.swing.JLabel lblAvdNamn;
    private javax.swing.JLabel lblAvdStad;
    private javax.swing.JLabel lblAvdTelefon;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblAvdid;
    private javax.swing.JLabel lblSokHandlaggare;
    private javax.swing.JTable tblVisaAnstallda;
    private javax.swing.JTextField txtSokHandlaggare;
    // End of variables declaration//GEN-END:variables
}
