/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;


/**
 * en jFrame klass som ger användare en överblick över deras avdelning.
 * Finns även en sökfunktion för att hitta specifika handläggare. 
 */
public class AvdelningJframe extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private AvdelningSQL avdelningSQL;
 
  

  //  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvdelningJframe.class.getName());

    /**
     * Creates new form AvdelningJframe
     */
    public AvdelningJframe(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.avdelningSQL = new AvdelningSQL(idb);
        initComponents();
        tblVisaAnstallda.setVisible(true);
        tblVisaAnstallda.getTableHeader().setBackground(new Color(61, 176, 75));
        tblVisaAnstallda.getTableHeader().setForeground(Color.WHITE);
       

        fyllAvdelningsInfo();
        visaAvdAnstallda();
        
        tblVisaAnstallda.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblVisaAnstallda.getColumnModel().getColumn(1).setPreferredWidth(10);
        tblVisaAnstallda.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblVisaAnstallda.getColumnModel().getColumn(3).setPreferredWidth(90);
        tblVisaAnstallda.getColumnModel().getColumn(4).setPreferredWidth(20);
    }   

    private void fyllAvdelningsInfo() {
        try {
            String sqlFraga = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            String avdidString = idb.fetchSingle(sqlFraga);
            int avdid = Integer.parseInt(avdidString);

            AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
            Avdelning avd = avdelningSQL.hamtaAvdelningMedId(avdid);

            lblAvdid.setText("avd-ID: " + String.valueOf(avd.getAvdid()));
            lblAvdNamn.setText(avd.getNamn());
            lblAvdAdress.setText(avd.getAdress());
            lblAvdStad.setText("Stad: " + avd.getStad());
            lblAvdEpost.setText(avd.getEpost());
            lblAvdTelefon.setText(avd.getTelefon());
            lblAvdChef.setText("Chef: " + avd.getChef());
            lblAvdBeskrivning.setText(avd.getBeskrivning());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void visaAvdAnstallda() { // visar alla anstallda (samt deras info) på avdelningen i en tabell.
        try {
            String sqlFraga = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            String avdidString = idb.fetchSingle(sqlFraga);
            int avdid = Integer.parseInt (idb.fetchSingle(sqlFraga));
            
            AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
            var visaAnstallda = avdelningSQL.hamtaPersonalForAvdelning(avdid);
            
            DefaultTableModel modell = (DefaultTableModel) tblVisaAnstallda.getModel();
            modell.setRowCount(0);
            
            for (var person : visaAnstallda) {
                 modell.addRow(new Object[]{
                     person.get("aid"), person.get("fornamn"), person.get("efternamn"), person.get("epost"), person.get("telefon")});
            }
                 tblVisaAnstallda.setVisible(!visaAnstallda.isEmpty());
            } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Anstallda från avdelningen kunde inte hämtas.");
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
           
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lblAvdEpost1 = new javax.swing.JLabel();
        txtSokHandlaggare = new javax.swing.JTextField();
        lblSokHandlaggare = new javax.swing.JLabel();
        lblAvdid = new javax.swing.JLabel();
        lblAvdNamn = new javax.swing.JLabel();
        lblAvdAdress = new javax.swing.JLabel();
        lblAvdStad = new javax.swing.JLabel();
        lblAvdEpost = new javax.swing.JLabel();
        lblAvdTelefon = new javax.swing.JLabel();
        lblAvdChef = new javax.swing.JLabel();
        lblAvdBeskrivning = new javax.swing.JLabel();
        btnSokHandlaggare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisaAnstallda = new javax.swing.JTable();
        btnRedigeraAvdelning = new javax.swing.JButton();
        lblAvdAnstallda = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnAterstallTabell = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        lblAvdEpost1.setText("epost");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSokHandlaggare.setText("Sök efter handläggare:");

        lblAvdid.setText("avdid");

        lblAvdNamn.setText("namn");

        lblAvdAdress.setText("adress");

        lblAvdStad.setText("stad");

        lblAvdEpost.setText("epost");

        lblAvdTelefon.setText("telefon");

        lblAvdChef.setText("chef");

        lblAvdBeskrivning.setText("beskrivning");

        btnSokHandlaggare.setBackground(new java.awt.Color(1, 174, 217));
        btnSokHandlaggare.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSokHandlaggare.setForeground(new java.awt.Color(255, 255, 255));
        btnSokHandlaggare.setText("Sök");
        btnSokHandlaggare.addActionListener(this::btnSokHandlaggareActionPerformed);

        tblVisaAnstallda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "aid", "fornamn", "efternamn", "epost", "telefon"
            }
        ));
        tblVisaAnstallda.setGridColor(new java.awt.Color(0, 0, 0));
        tblVisaAnstallda.setMinimumSize(new java.awt.Dimension(1, 80));
        tblVisaAnstallda.setRequestFocusEnabled(false);
        tblVisaAnstallda.setRowSelectionAllowed(true);
        jScrollPane1.setViewportView(tblVisaAnstallda);

        btnRedigeraAvdelning.setBackground(new java.awt.Color(1, 174, 217));
        btnRedigeraAvdelning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRedigeraAvdelning.setForeground(new java.awt.Color(255, 255, 255));
        btnRedigeraAvdelning.setText("Redigera avdelningar");
        btnRedigeraAvdelning.addActionListener(this::btnRedigeraAvdelningActionPerformed);

        lblAvdAnstallda.setText("Anställda på avdelningen:");

        btnTillbaka.setBackground(new java.awt.Color(249, 181, 18));
        btnTillbaka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        btnAterstallTabell.setBackground(new java.awt.Color(235, 28, 46));
        btnAterstallTabell.setForeground(new java.awt.Color(255, 255, 255));
        btnAterstallTabell.setText("X");
        btnAterstallTabell.addActionListener(this::btnAterstallTabellActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAvdNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAvdAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblAvdChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAvdTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(lblAvdEpost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAvdStad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAvdAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(btnRedigeraAvdelning)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSokHandlaggare)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSokHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAterstallTabell))
                    .addComponent(lblSokHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvdAnstallda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSokHandlaggare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(txtSokHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAterstallTabell, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRedigeraAvdelning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSokHandlaggare)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokHandlaggareActionPerformed
        /* när en användare trycker på knappen ändras visaAnstallda tabellen till att endast 
           visa handläggare vars namn (eller epost) matchar det användaren skrev in i sökrutan.
        */
        String sokterm = txtSokHandlaggare.getText();
        try {
            String sqlFraga = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            int avdid = Integer.parseInt(idb.fetchSingle(sqlFraga));
            
            AvdelningSQL avdelningSQL = new AvdelningSQL(idb); 
            var sokResultat = avdelningSQL.sokHandlaggare(avdid, sokterm);
            
             DefaultTableModel modell = (DefaultTableModel) tblVisaAnstallda.getModel();
             modell.setRowCount(0);
             
             for (var person : sokResultat) {
                 modell.addRow(new Object[]{
                     person.get("aid"), person.get("fornamn"), person.get("efternamn"), person.get("epost"), person.get("telefon")});
             }
            tblVisaAnstallda.setVisible(!sokResultat.isEmpty());   
            lblAvdAnstallda.setText("Handläggare på avdelningen:");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSokHandlaggareActionPerformed

    private void btnRedigeraAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraAvdelningActionPerformed
        //Endast admin har behörigheten att ändra avdelningar, här kontrolleras det att den inloggade användaren är en admin.
        if (ValAvRoll.arAdmin(idb, inloggadAnvandare)){
        new AdminKontrollPanelAvdelning(idb).setVisible(true);
        } else {
        JOptionPane.showMessageDialog(this, "Endast administratörer har behörigheten att redigera avdelningar.");
        }
    }//GEN-LAST:event_btnRedigeraAvdelningActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnAterstallTabellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAterstallTabellActionPerformed
        // När användaren trycker på knappen X återställs tabellen till att visa alla anstallda på avdelningen. 
        txtSokHandlaggare.setText("");
        lblAvdAnstallda.setText("Personal på avdelningen: ");
        visaAvdAnstallda();
    }//GEN-LAST:event_btnAterstallTabellActionPerformed
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAterstallTabell;
    private javax.swing.JButton btnRedigeraAvdelning;
    private javax.swing.JButton btnSokHandlaggare;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAvdAdress;
    private javax.swing.JLabel lblAvdAnstallda;
    private javax.swing.JLabel lblAvdBeskrivning;
    private javax.swing.JLabel lblAvdChef;
    private javax.swing.JLabel lblAvdEpost;
    private javax.swing.JLabel lblAvdEpost1;
    private javax.swing.JLabel lblAvdNamn;
    private javax.swing.JLabel lblAvdStad;
    private javax.swing.JLabel lblAvdTelefon;
    private javax.swing.JLabel lblAvdid;
    private javax.swing.JLabel lblSokHandlaggare;
    private javax.swing.JTable tblVisaAnstallda;
    private javax.swing.JTextField txtSokHandlaggare;
    // End of variables declaration//GEN-END:variables
}
