/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;

/**
 *
 * @author tovehanssons
 */
public class Hallbarhetsmal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hallbarhetsmal.class.getName());
    private InfDB idb;
    private String inloggadAnvandare;
    private java.util.ArrayList<String> beskrivningar = new java.util.ArrayList<>();
    /**
     * Creates new form Hallbarhetsmal
     */
   public Hallbarhetsmal(InfDB idb, String inloggadAnvandare) {
    this.idb = idb;
    this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        
    jtHallbarhetsmal.setFont(new Font("SansSerif", Font.PLAIN, 14));
    jtHallbarhetsmal.setRowHeight(22);

    jtHallbarhetsmal.getTableHeader()
    .setFont(new Font("SansSerif", Font.BOLD, 14));

    jtHallbarhetsmal.getColumnModel().getColumn(0).setPreferredWidth(650);
    jtHallbarhetsmal.getColumnModel().getColumn(1).setPreferredWidth(170);
    jtHallbarhetsmal.getColumnModel().getColumn(2).setPreferredWidth(120);
        
    fyllHallbarhetsmalTabell();
    laggTillTabellLyssnare();
    
    if (jtHallbarhetsmal.getRowCount() > 0) {
    jtHallbarhetsmal.setRowSelectionInterval(0, 0);
    txtaHallbarhetsmal.setText(beskrivningar.get(0));
}

    txtaHallbarhetsmal.setLineWrap(true);
    txtaHallbarhetsmal.setWrapStyleWord(true);
    txtaHallbarhetsmal.setEditable(false);
    
    }
   
   private void fyllHallbarhetsmalTabell() {
    DefaultTableModel modell =
            (DefaultTableModel) jtHallbarhetsmal.getModel();

    modell.setRowCount(0);
    beskrivningar.clear();

    try {
        String sqlFraga = "SELECT namn, malnummer, prioritet, beskrivning FROM"
                + " hallbarhetsmal ORDER BY malnummer";

        ArrayList<HashMap<String, String>> resultat =
                idb.fetchRows(sqlFraga);

        for (HashMap<String, String> rad : resultat) {
            modell.addRow(new Object[]{
                rad.get("namn"),
                rad.get("malnummer"),
                rad.get("prioritet")
            });

            beskrivningar.add(rad.get("beskrivning"));
        }

    } catch (InfException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
}
   private void laggTillTabellLyssnare() {
    jtHallbarhetsmal.getSelectionModel()
        .addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {
            int rad = jtHallbarhetsmal.getSelectedRow();

            if (rad >= 0) {
                txtaHallbarhetsmal.setText(
                        beskrivningar.get(rad)
                );
            }
        }
    });
}   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtHallbarhetsmal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaHallbarhetsmal = new javax.swing.JTextArea();
        lblInfo = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblHallbarhetsmal = new javax.swing.JLabel();
        btnTillbakaMal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtHallbarhetsmal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Namn", "Målnummer", "Prioritet"
            }
        ));
        jScrollPane1.setViewportView(jtHallbarhetsmal);

        txtaHallbarhetsmal.setColumns(20);
        txtaHallbarhetsmal.setRows(5);
        jScrollPane2.setViewportView(txtaHallbarhetsmal);

        lblInfo.setText("Information");

        lblBeskrivning.setText("Beskrivning");

        lblHallbarhetsmal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblHallbarhetsmal.setText("Hållbarhetsmål");

        btnTillbakaMal.setText("Tillbaka");
        btnTillbakaMal.addActionListener(this::btnTillbakaMalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbakaMal)
                    .addComponent(lblInfo)
                    .addComponent(lblHallbarhetsmal)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeskrivning))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHallbarhetsmal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo)
                    .addComponent(lblBeskrivning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnTillbakaMal)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaMalActionPerformed
        Meny meny = new Meny(idb, inloggadAnvandare);
    meny.setVisible(true);
    this.dispose(); // stänger Hallbarhetsmal
    }//GEN-LAST:event_btnTillbakaMalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Hallbarhetsmal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbakaMal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtHallbarhetsmal;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblHallbarhetsmal;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTextArea txtaHallbarhetsmal;
    // End of variables declaration//GEN-END:variables
}
