/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class Inloggning extends javax.swing.JFrame {

    private InfDB idb;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inloggning.class.getName());

    /**
     * Creates new form Inloggning
     */
    public Inloggning(InfDB idb) {
        this.idb = idb;
        initComponents();
        this.setLocationRelativeTo(null);
        
        getContentPane().setBackground(Color.WHITE);
        lblFelMeddelande.setVisible(false);

        getContentPane().setBackground(Color.WHITE);

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/ngo_2024/bilder/sdg2.png"));

        int targetWidth = 320;
        int targetHeight = (originalIcon.getIconHeight() * targetWidth) / originalIcon.getIconWidth();

        Image scaledImage = originalIcon.getImage().getScaledInstance(targetWidth, targetHeight, Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblepost = new javax.swing.JLabel();
        lbllosenord = new javax.swing.JLabel();
        txtepost = new javax.swing.JTextField();
        txtlosenord = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        lblFelMeddelande = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblepost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblepost.setText("EPOST:");

        lbllosenord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllosenord.setText("LÖSENORD:");

        txtepost.setForeground(new java.awt.Color(51, 51, 51));
        txtepost.addActionListener(this::txtepostActionPerformed);

        txtlosenord.setForeground(new java.awt.Color(51, 51, 51));
        txtlosenord.addActionListener(this::txtlosenordActionPerformed);

        btnlogin.setBackground(new java.awt.Color(51, 51, 51));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("LOGGA IN");
        btnlogin.addActionListener(this::btnloginActionPerformed);

        lblFelMeddelande.setForeground(new java.awt.Color(204, 0, 51));
        lblFelMeddelande.setText("Felaktigt E-post eller lösenord");

        jLabel1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbllosenord)
                                    .addComponent(lblepost, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtepost, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblFelMeddelande)
                            .addComponent(btnlogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblepost)
                    .addComponent(txtepost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelMeddelande)
                .addGap(18, 18, 18)
                .addComponent(btnlogin)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtepostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtepostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtepostActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String ePost = txtepost.getText();
        String losenord = txtlosenord.getText();
        try {
            String sqlFraga = "SELECT losenord FROM anstalld WHERE epost = '" + ePost + "'";
            // System.out.println(sqlFraga);
            String dblosen = idb.fetchSingle(sqlFraga);
            if (losenord.equals(dblosen)) {
                new Meny(idb, ePost).setVisible(true);
                this.setVisible(false);
            } else {
                lblFelMeddelande.setVisible(true);
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtlosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlosenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> new Inloggning().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFelMeddelande;
    private javax.swing.JLabel lblepost;
    private javax.swing.JLabel lbllosenord;
    private javax.swing.JTextField txtepost;
    private javax.swing.JTextField txtlosenord;
    // End of variables declaration//GEN-END:variables
}
