/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import javax.swing.JOptionPane;

/**
 * den här klassen låter administratörer lägga till nya avdelningar i databasen.
 */
public class LaggTillAvdelning extends javax.swing.JFrame {
    private InfDB idb;
    private int avdid;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaggTillAvdelning.class.getName());

    /**
     * Creates new form LaggTillAvdelning
     */
    public LaggTillAvdelning(InfDB idb) {
        this.idb = idb;
        initComponents();
        dropDownChef.removeAllItems();
        dropDownChef.addItem("Välj chef...");
        dropDownStad.removeAllItems();
        dropDownStad.addItem("Välj stad...");
        fyllChefDropDown();
        fyllStadDropDown();
    }

    private void fyllChefDropDown() { 
      try { 
          AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
          var handlaggare = avdelningSQL.hamtaAllaHandlaggare();
          
          System.out.println("Antal handläggare: " + handlaggare.size());

          for (var h : handlaggare) {
              String item = h.get("aid") + " - " + h.get("fornamn") + " " + h.get("efternamn");
              dropDownChef.addItem(item);
          }
          for (int i = 0; i < dropDownChef.getItemCount(); i++) {
              String item = dropDownChef.getItemAt(i); 
          }
      } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Kunde inte visa chefer: " + e.getMessage());
      }
    }
    
    private void fyllStadDropDown() {
        try {
           AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
           var stader = avdelningSQL.hamtaAllaStader();
           
           for (var stad : stader) {
               String item = stad.get ("sid") + " - " + stad.get("namn");
               dropDownStad.addItem(item);
           }
           for (int i = 0; i < dropDownStad.getItemCount(); i++) {
       }
       } catch (Exception e) {
           System.out.println("Kunde inte visa städer: " + e.getMessage());
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNyAvdelning = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        lblAvdNamn = new javax.swing.JLabel();
        lblAvdAdress = new javax.swing.JLabel();
        lblAvdStad = new javax.swing.JLabel();
        lblAvdEpost = new javax.swing.JLabel();
        lblAvdTelefon = new javax.swing.JLabel();
        lblAvdChef = new javax.swing.JLabel();
        lblAvdBeskrivning = new javax.swing.JLabel();
        txtAvdNamn = new javax.swing.JTextField();
        txtAvdAdress = new javax.swing.JTextField();
        txtAvdEpost = new javax.swing.JTextField();
        txtAvdTelefon = new javax.swing.JTextField();
        txtAvdBeskrivning = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        dropDownChef = new javax.swing.JComboBox<>();
        dropDownStad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNyAvdelning.setText("Ny avdelning:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        lblAvdNamn.setText("Namn:");

        lblAvdAdress.setText("Adress:");

        lblAvdStad.setText("Stad:");

        lblAvdEpost.setText("Epost:");

        lblAvdTelefon.setText("Telefon:");

        lblAvdChef.setText("Chef:");

        lblAvdBeskrivning.setText("Beskrivning:");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNyAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(lblAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTillbaka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAvdNamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(txtAvdAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(txtAvdEpost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(txtAvdTelefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(txtAvdBeskrivning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(dropDownChef, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dropDownStad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSpara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNyAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvdNamn)
                    .addComponent(txtAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdAdress)
                    .addComponent(txtAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdStad)
                    .addComponent(dropDownStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdEpost)
                    .addComponent(txtAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdTelefon)
                    .addComponent(txtAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdChef)
                    .addComponent(dropDownChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdBeskrivning)
                    .addComponent(txtAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // Tillbakaknapp
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // Sparar det användaren har angett och validerar namn, epost, telefon och adress.
        try {
            String namn = txtAvdNamn.getText();
            String adress = txtAvdAdress.getText();
            String valdStad = (String) dropDownStad.getSelectedItem();
            int stad = Integer.parseInt(valdStad.split(" - ")[0]);
            String epost = txtAvdEpost.getText();
            String telefon = txtAvdTelefon.getText();
            String valdChef = (String) dropDownChef.getSelectedItem();
            int chef = Integer.parseInt(valdChef.split(" - ")[0]);
            String beskrivning = txtAvdBeskrivning.getText();

            if (!Validering.ValideraNamn(namn)) {
                JOptionPane.showMessageDialog(this, "Ogiltigt namn.");
                return;
            }
            if (!Validering.ValideraEpost(epost)) {
                JOptionPane.showMessageDialog(this, "ogiltig e-postadress.");
                return;
            }
            if (!Validering.ValideraTelefon(telefon)) {
                JOptionPane.showMessageDialog(this, "Ogiltigt telefonnummer.");
                return;
            }
            if (!Validering.ValideraAdress(adress)) {
                JOptionPane.showMessageDialog(this, "Ogiltig adress.");
                return;
            }

           AvdelningSQL avdelningSQL = new AvdelningSQL(idb); 
            int nyttAvdid = avdelningSQL.skapaNyttAvdid();
            System.out.println("Nytt avdid: " + nyttAvdid);

            avdelningSQL.laggTillAvdelning(nyttAvdid, namn, beskrivning, adress, epost, telefon, stad, chef);

            JOptionPane.showMessageDialog(this, "Ny avdelning med namn " + namn + " har skapats.");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fel vid skapandet av ny avdelning: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new LaggTillAvdelning().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> dropDownChef;
    private javax.swing.JComboBox<String> dropDownStad;
    private javax.swing.JLabel lblAvdAdress;
    private javax.swing.JLabel lblAvdBeskrivning;
    private javax.swing.JLabel lblAvdChef;
    private javax.swing.JLabel lblAvdEpost;
    private javax.swing.JLabel lblAvdNamn;
    private javax.swing.JLabel lblAvdStad;
    private javax.swing.JLabel lblAvdTelefon;
    private javax.swing.JLabel lblNyAvdelning;
    private javax.swing.JTextField txtAvdAdress;
    private javax.swing.JTextField txtAvdBeskrivning;
    private javax.swing.JTextField txtAvdEpost;
    private javax.swing.JTextField txtAvdNamn;
    private javax.swing.JTextField txtAvdTelefon;
    // End of variables declaration//GEN-END:variables
}
