/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.awt.Font;
import javax.swing.JTable;

public class PartnersFonster extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(PartnersFonster.class.getName());

    private InfDB idb;
    private String inloggadAnvandare;
    private ArrayList<Partners> visadePartners = new ArrayList<>();

    public PartnersFonster(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;

        initComponents();
        
    jtPartners.setFont(new Font("SansSerif", Font.PLAIN, 12));
    jtPartners.setRowHeight(22);

    jtPartners.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));


    jtPartners.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);


    jtPartners.getColumnModel().getColumn(0).setPreferredWidth(190); // Namn
    jtPartners.getColumnModel().getColumn(1).setPreferredWidth(130); // Kontaktperson
    jtPartners.getColumnModel().getColumn(2).setPreferredWidth(190); // Kontaktepost
    jtPartners.getColumnModel().getColumn(3).setPreferredWidth(120); // Telefon
    jtPartners.getColumnModel().getColumn(4).setPreferredWidth(150); // Adress
    jtPartners.getColumnModel().getColumn(5).setPreferredWidth(160); // Branch
    jtPartners.getColumnModel().getColumn(6).setPreferredWidth(50); // Stad


        
        
        cbPartners.removeAllItems();
        
        sattBehorighet();

        if (ValAvRoll.arProjektchef(idb, inloggadAnvandare)) {
            fyllProjektCombo();
        }

        fyllPartnersTabell();

        cbPartners.addActionListener(e -> {
            if (ValAvRoll.arProjektchef(idb, inloggadAnvandare)) {
                fyllPartnersTabell();
            }
        });
    }

    private void sattBehorighet() {
        boolean arAdmin = ValAvRoll.arAdmin(idb, inloggadAnvandare);
        boolean arProjektchef = ValAvRoll.arProjektchef(idb, inloggadAnvandare);

       btnLaggtillPartners.setVisible(arAdmin || arProjektchef);
       btnTabortPartners.setVisible(arAdmin || arProjektchef);
       btnAndraPartners.setVisible(arAdmin);

        cbPartners.setVisible(arProjektchef);

        if (!arProjektchef) {
            cbPartners.removeAllItems();
        }
    }

private void fyllPartnersTabell() {
    DefaultTableModel model = (DefaultTableModel) jtPartners.getModel();
    model.setRowCount(0);

    visadePartners.clear(); 

    ArrayList<Partners> lista;

if (ValAvRoll.arAdmin(idb, inloggadAnvandare)) {

    // Admin ser alla partners
    lista = Partners.hamtaAlla(idb);

} else if (ValAvRoll.arProjektchef(idb, inloggadAnvandare)) {

    // Projektchef ser partners för valt projekt
    String projektPid = (String) cbPartners.getSelectedItem();
    lista = (projektPid == null)
            ? new ArrayList<>()
            : Partners.hamtaForProjekt(idb, projektPid);

} else if (ValAvRoll.arHandlaggare(idb, inloggadAnvandare)) {

    lista = Partners.hamtaForHandlaggare(idb, inloggadAnvandare);

} else {
    lista = new ArrayList<>();
}


    for (Partners p : lista) {
        visadePartners.add(p);   

        model.addRow(new Object[]{
            p.getNamn(),
            p.getKontaktperson(),
            p.getKontaktepost(),
            p.getTelefon(),
            p.getAdress(),
            p.getBranch(),
            p.getStad()
        });
    }
}

        public void laddaOmPartners() {
        fyllPartnersTabell();
        }


    private void fyllProjektCombo() {
        cbPartners.removeAllItems();
        Projektchef pc = new Projektchef(idb, inloggadAnvandare);

        for (String pid : pc.hamtaEgnaProjekt()) {
            cbPartners.addItem(pid);
        }
        
        if (cbPartners.getItemCount() > 0) {
    cbPartners.setSelectedIndex(0);
}
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPartners = new javax.swing.JTable();
        lblPartners = new javax.swing.JLabel();
        cbPartners = new javax.swing.JComboBox<>();
        btnAndraPartners = new javax.swing.JButton();
        btnTabortPartners = new javax.swing.JButton();
        btnLaggtillPartners = new javax.swing.JButton();
        btnTbPartners = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Namn", "Kontaktperson", "Kontaktepost", "Telefon", "Adress", "Branch", "Stad"
            }
        ));
        jScrollPane1.setViewportView(jtPartners);

        lblPartners.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPartners.setText("Partners");

        cbPartners.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAndraPartners.setText("Ändra");
        btnAndraPartners.addActionListener(this::btnAndraPartnersActionPerformed);

        btnTabortPartners.setText("Ta bort");
        btnTabortPartners.addActionListener(this::btnTabortPartnersActionPerformed);

        btnLaggtillPartners.setText("Lägg till");
        btnLaggtillPartners.addActionListener(this::btnLaggtillPartnersActionPerformed);

        btnTbPartners.setText("Tillbaka");
        btnTbPartners.addActionListener(this::btnTbPartnersActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTbPartners)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLaggtillPartners)
                        .addGap(18, 18, 18)
                        .addComponent(btnTabortPartners)
                        .addGap(18, 18, 18)
                        .addComponent(btnAndraPartners))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPartners)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraPartners)
                    .addComponent(btnTabortPartners)
                    .addComponent(btnLaggtillPartners)
                    .addComponent(btnTbPartners))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraPartnersActionPerformed
            int rad = jtPartners.getSelectedRow();

    if (rad == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Välj en partner först.");
        return;
    }

    Partners valdPartner = visadePartners.get(rad);
    String pid = valdPartner.getPid();

    new RedigeraPartners(this, idb, pid).setVisible(true);
    
    }//GEN-LAST:event_btnAndraPartnersActionPerformed

    private void btnLaggtillPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggtillPartnersActionPerformed
        new RedigeraPartners(this, idb, null).setVisible(true);
   
    }//GEN-LAST:event_btnLaggtillPartnersActionPerformed

    private void btnTabortPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabortPartnersActionPerformed

    int rad = jtPartners.getSelectedRow();

    if (rad == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Välj en partner först.");
        return;
    }

    Partners valdPartner = visadePartners.get(rad);
    String partnerPid = valdPartner.getPid();

    int svar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Vill du verkligen ta bort '" + valdPartner.getNamn() + "'?",
            "Bekräfta borttagning",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (svar != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    try {
        if (ValAvRoll.arProjektchef(idb, inloggadAnvandare)) {

            String projektPid = (String) cbPartners.getSelectedItem();
            if (projektPid == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Välj ett projekt först.");
                return;
            }

            idb.delete(
                "DELETE FROM projekt_partner " +
                "WHERE pid = '" + projektPid + "' " +
                "AND partner_pid = '" + partnerPid + "'"
            );

        } else if (ValAvRoll.arAdmin(idb, inloggadAnvandare)) {

            idb.delete("DELETE FROM projekt_partner WHERE partner_pid = '" + partnerPid + "'");
            idb.delete("DELETE FROM partner WHERE pid = '" + partnerPid + "'");
        }

        laddaOmPartners();

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
    }

    }//GEN-LAST:event_btnTabortPartnersActionPerformed

    private void btnTbPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbPartnersActionPerformed
        dispose();
    }//GEN-LAST:event_btnTbPartnersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new PartnersFonster().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraPartners;
    private javax.swing.JButton btnLaggtillPartners;
    private javax.swing.JButton btnTabortPartners;
    private javax.swing.JButton btnTbPartners;
    private javax.swing.JComboBox<String> cbPartners;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPartners;
    private javax.swing.JLabel lblPartners;
    // End of variables declaration//GEN-END:variables
}
