/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class PartnersFonster extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(PartnersFonster.class.getName());

    private InfDB idb;
    private String inloggadAnvandare;

    public PartnersFonster(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;

        initComponents();
        
        cbPartners.removeAllItems();
        
        sattBehorighet();

        if (ValAvRoll.arProjektchef(idb, inloggadAnvandare)) {
            fyllProjektCombo();
        }

        fyllPartnersTabell();

        cbPartners.addActionListener(e -> {
            if (ValAvRoll.arProjektchef(idb, inloggadAnvandare)) {
                fyllPartnersTabell();
            }
        });
    }

    private void sattBehorighet() {
        boolean arAdmin = ValAvRoll.arAdmin(idb, inloggadAnvandare);
        boolean arProjektchef = ValAvRoll.arProjektchef(idb, inloggadAnvandare);

        btnLaggtillPartners.setVisible(arAdmin);
        btnTabortPartners.setVisible(arAdmin);
        btnAndraPartners.setVisible(arAdmin);

        cbPartners.setVisible(arProjektchef);

        if (!arProjektchef) {
            cbPartners.removeAllItems();
        }
    }

    private void fyllPartnersTabell() {
        DefaultTableModel model = (DefaultTableModel) jtPartners.getModel();
        model.setRowCount(0);

        ArrayList<Partners> lista;

        boolean arAdmin = ValAvRoll.arAdmin(idb, inloggadAnvandare);
        boolean arHandlaggare = ValAvRoll.arHandlaggare(idb, inloggadAnvandare);
        boolean arProjektchef = ValAvRoll.arProjektchef(idb, inloggadAnvandare);

        if (arAdmin) {
            lista = Partners.hamtaAlla(idb);
        } else if (arHandlaggare) {
            lista = Partners.hamtaForHandlaggare(idb, inloggadAnvandare);
        } else if (arProjektchef) {
            String valtPid = (String) cbPartners.getSelectedItem();
            if (valtPid == null) {
                lista = new ArrayList<>();
            } else {
                lista = Partners.hamtaForProjekt(idb, valtPid);
            }
        } else {
            lista = new ArrayList<>();
        }

        for (Partners p : lista) {
            model.addRow(new Object[]{
                p.getNamn(),
                p.getKontaktperson(),
                p.getKontaktepost(),
                p.getTelefon(),
                p.getAdress(),
                p.getBranch(),
                p.getStad()
            });
        }
    }

    private void fyllProjektCombo() {
        cbPartners.removeAllItems();
        Projektchef pc = new Projektchef(idb, inloggadAnvandare);

        for (String pid : pc.hamtaEgnaProjekt()) {
            cbPartners.addItem(pid);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPartners = new javax.swing.JTable();
        lblPartners = new javax.swing.JLabel();
        cbPartners = new javax.swing.JComboBox<>();
        btnAndraPartners = new javax.swing.JButton();
        btnTabortPartners = new javax.swing.JButton();
        btnLaggtillPartners = new javax.swing.JButton();
        btnTbPartners = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Namn", "Kontaktperson", "Kontaktepost", "Telefon", "Adress", "Branch", "Stad"
            }
        ));
        jScrollPane1.setViewportView(jtPartners);

        lblPartners.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPartners.setText("Partners");

        cbPartners.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAndraPartners.setText("Ändra");
        btnAndraPartners.addActionListener(this::btnAndraPartnersActionPerformed);

        btnTabortPartners.setText("Ta bort");

        btnLaggtillPartners.setText("Lägg till");

        btnTbPartners.setText("Tillbaka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTbPartners)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLaggtillPartners)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTabortPartners)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAndraPartners))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPartners)
                            .addGap(585, 585, 585))
                        .addComponent(cbPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblPartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(cbPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLaggtillPartners)
                            .addComponent(btnTabortPartners)
                            .addComponent(btnAndraPartners))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTbPartners)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraPartnersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraPartnersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new PartnersFonster().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraPartners;
    private javax.swing.JButton btnLaggtillPartners;
    private javax.swing.JButton btnTabortPartners;
    private javax.swing.JButton btnTbPartners;
    private javax.swing.JComboBox<String> cbPartners;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPartners;
    private javax.swing.JLabel lblPartners;
    // End of variables declaration//GEN-END:variables
}
