/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author user
 */
public class Person extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private String fullstandigtnamn;
    private String anvandaradress;
    private String anvandartelefon;
    private String anvandarID; 
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Person.class.getName());

    /**
     * Creates new form Person
     */
    public Person(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        
        initComponents();
        
        getFullstandigtnamn();
        getAnvandarAdress();
        getAnvandarTelefon();
        getAnvandarID();
        
        lblfulltnamn.setText(fullstandigtnamn);
        lblanvandaradress.setText(anvandaradress);
        lblanvandartelefon.setText(anvandartelefon);
        lblanvandarID.setText(anvandarID);
       
    }
    
    public void getFullstandigtnamn(){
        try{
        String sqlFraga = "SELECT fornamn FROM anstalld WHERE ePost = '" + inloggadAnvandare + "'";
        String sqlFraga2 = "SELECT efternamn FROM anstalld WHERE ePost = '" + inloggadAnvandare + "'";
        String fornamnEfternamn = idb.fetchSingle(sqlFraga) + " " + idb.fetchSingle(sqlFraga2);
        
        if (fornamnEfternamn != null) {
            this.fullstandigtnamn = fornamnEfternamn;
        }
        }catch(Exception e){
        }
    } 
    
    public void getAnvandarTelefon() {
    try {
        String sqlFraga = "SELECT telefon FROM anstalld WHERE ePost = '" + inloggadAnvandare + "'";
        String telefon = idb.fetchSingle(sqlFraga);

        if (telefon != null) {
            this.anvandartelefon = telefon;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    public void getAnvandarAdress() {
    try {
        String sqlFraga = "SELECT adress FROM anstalld WHERE ePost = '" + inloggadAnvandare + "'";
        String adress = idb.fetchSingle(sqlFraga);

        if (adress != null) {
            this.anvandaradress = adress;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    
    public void getAnvandarID() {
    try {
        String sqlFraga = "SELECT aid FROM anstalld WHERE ePost = '" + inloggadAnvandare + "'";
        String id = idb.fetchSingle(sqlFraga);

        if (id != null) {
            this.anvandarID = id;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    // KOD FÖR ATT FÅ IN SAKER FRÅN DATABASEN TILL EN LABEL ^

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblanvandarepost = new javax.swing.JLabel();
        lbladress = new javax.swing.JLabel();
        lbltelefon = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        AnställdID = new javax.swing.JLabel();
        lblpersonnamn = new javax.swing.JLabel();
        lblfulltnamn = new javax.swing.JLabel();
        lblanvandaradress = new javax.swing.JLabel();
        lblanvandartelefon = new javax.swing.JLabel();
        lblanvandarID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblanvandarepost.setText("Epost:");

        lbladress.setText("Adress");

        lbltelefon.setText("Telefon");

        jToggleButton1.setText("Ändra personuppgifter");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        AnställdID.setText("AnställdID");

        lblpersonnamn.setText("Namn");

        lblfulltnamn.setText("Namn");

        lblanvandaradress.setText("Adress");

        lblanvandartelefon.setText("Telefonnummer");

        lblanvandarID.setText("ID");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Hejsan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbltelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblanvandarepost)
                                            .addGap(3, 3, 3)))
                                    .addComponent(AnställdID)
                                    .addComponent(lbladress))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblanvandarID)
                                    .addComponent(lblanvandartelefon)
                                    .addComponent(lblanvandaradress)
                                    .addComponent(lblpersonnamn)))
                            .addComponent(jToggleButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblfulltnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfulltnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpersonnamn)
                    .addComponent(lblanvandarepost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladress)
                    .addComponent(lblanvandaradress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefon)
                    .addComponent(lblanvandartelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblanvandarID)
                    .addComponent(AnställdID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       /*Uppgiftsandrare newframe = new Uppgiftsandrare(idb, inloggadAnvandare);
       newframe.setVisible(true);
       newframe.toFront();*/
       AndraUppgifter andraUppgifter = new AndraUppgifter(idb, inloggadAnvandare);
       andraUppgifter.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Meny newframe = new Meny(idb, inloggadAnvandare);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Person().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnställdID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblanvandarID;
    private javax.swing.JLabel lblanvandaradress;
    private javax.swing.JLabel lblanvandarepost;
    private javax.swing.JLabel lblanvandartelefon;
    private javax.swing.JLabel lblfulltnamn;
    private javax.swing.JLabel lblpersonnamn;
    private javax.swing.JLabel lbltelefon;
    // End of variables declaration//GEN-END:variables
}
