/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import java.awt.Color;
import oru.inf.InfDB;
import javax.swing.JOptionPane;

/**
 * Gör det möjligt för adminer att redigera befintliga avdelningar.
 */
public class RedigeraAvdelning extends javax.swing.JFrame {

    private InfDB idb;
    private int avdid;
    private int nuvarandeChefId;
    private int nuvarandeStadId;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RedigeraAvdelning.class.getName());

    /**
     * Creates new form RedigeraAvdelning
     */
    public RedigeraAvdelning(InfDB idb, int avdid) {
        this.idb = idb;
        this.avdid = avdid;
        getContentPane().setBackground(Color.WHITE);
        initComponents();
        this.setLocationRelativeTo(null);

        dropDownChef.removeAllItems();
        fyllFalt();
        fyllChefDropDown();
        fyllStadDropDown();
    }

    private void fyllFalt() {
        try {
            AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
            Avdelning avd = avdelningSQL.hamtaAvdelningMedId(avdid);

            txtAvdid.setText(String.valueOf(avd.getAvdid()));
            txtAvdNamn.setText(avd.getNamn());
            txtAvdAdress.setText(avd.getAdress());
            txtAvdEpost.setText(avd.getEpost());
            txtAvdTelefon.setText(avd.getTelefon());
            txtAvdBeskrivning.setText(avd.getBeskrivning());
            nuvarandeChefId = Integer.parseInt(avd.getChef());
            nuvarandeStadId = Integer.parseInt(avd.getStad());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fyllChefDropDown() {
        try {
            AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
            var handlaggare = avdelningSQL.hamtaAllaHandlaggare();

            System.out.println("Antal anställda: " + handlaggare.size());

            for (var a : handlaggare) {
                String item = a.get("aid") + " - " + a.get("fornamn") + " " + a.get("efternamn");
                dropDownChef.addItem(item);
            }
            String nuvarandeChef = String.valueOf(nuvarandeChefId);
            for (int i = 0; i < dropDownChef.getItemCount(); i++) {
                String item = dropDownChef.getItemAt(i);
                if (item.startsWith(nuvarandeChef + " -")) {
                    dropDownChef.setSelectedIndex(i);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde inte visa chefer: " + e.getMessage());
        }
    }

    private void fyllStadDropDown() {
        try {
            AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
            var stader = avdelningSQL.hamtaAllaStader();

            for (var s : stader) {
                String item = s.get("sid") + " - " + s.get("namn");
                dropDownStad.addItem(item);
            }
            String nuvarandeStad = String.valueOf(nuvarandeStadId);
            for (int i = 0; i < dropDownStad.getItemCount(); i++) {
                String item = dropDownStad.getItemAt(i);
                if (item.startsWith(nuvarandeStad + " -")) {
                    dropDownStad.setSelectedIndex(i);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde inte visa städer: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRedigeraAvdelning = new javax.swing.JLabel();
        lblAvdid = new javax.swing.JLabel();
        lblAvdNamn = new javax.swing.JLabel();
        lblAvdAdress = new javax.swing.JLabel();
        lblAvdStad = new javax.swing.JLabel();
        lblAvdEpost = new javax.swing.JLabel();
        lblAvdTelefon = new javax.swing.JLabel();
        lblAvdChef = new javax.swing.JLabel();
        lblAvdBeskrivning = new javax.swing.JLabel();
        txtAvdid = new javax.swing.JTextField();
        txtAvdNamn = new javax.swing.JTextField();
        txtAvdAdress = new javax.swing.JTextField();
        txtAvdEpost = new javax.swing.JTextField();
        txtAvdTelefon = new javax.swing.JTextField();
        txtAvdBeskrivning = new javax.swing.JTextField();
        btnSparaAndringar = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        dropDownChef = new javax.swing.JComboBox<>();
        dropDownStad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRedigeraAvdelning.setText("Redigera avdelning:");

        lblAvdid.setText("Avdid:");

        lblAvdNamn.setText("Namn:");

        lblAvdAdress.setText("Adress:");

        lblAvdStad.setText("Stad:");

        lblAvdEpost.setText("Epost:");

        lblAvdTelefon.setText("Telefon:");

        lblAvdChef.setText("Chef:");

        lblAvdBeskrivning.setText("Beskrivning:");

        btnSparaAndringar.setBackground(new java.awt.Color(61, 176, 75));
        btnSparaAndringar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSparaAndringar.setForeground(new java.awt.Color(255, 255, 255));
        btnSparaAndringar.setText("Spara ");
        btnSparaAndringar.addActionListener(this::btnSparaAndringarActionPerformed);

        btnTillbaka.setBackground(new java.awt.Color(249, 181, 18));
        btnTillbaka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        dropDownChef.setBackground(new java.awt.Color(1, 174, 217));

        dropDownStad.setBackground(new java.awt.Color(1, 174, 217));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvdChef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvdStad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRedigeraAvdelning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(172, 172, 172)
                            .addComponent(btnSparaAndringar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dropDownStad, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropDownChef, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRedigeraAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdid)
                    .addComponent(txtAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdNamn)
                    .addComponent(txtAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdAdress)
                    .addComponent(txtAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdStad)
                    .addComponent(dropDownStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdEpost)
                    .addComponent(txtAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdTelefon)
                    .addComponent(txtAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdChef)
                    .addComponent(dropDownChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdBeskrivning)
                    .addComponent(txtAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSparaAndringar)
                    .addComponent(btnTillbaka))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaAndringarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaAndringarActionPerformed
        // Sparar admins ändringar, validerar namn, epost, telefonnummer och adress. 
        try {
            int avdid = Integer.parseInt(txtAvdid.getText());
            String namn = txtAvdNamn.getText();
            String adress = txtAvdAdress.getText();
            String valdStad = (String) dropDownStad.getSelectedItem();
            int stad = Integer.parseInt(valdStad.split(" - ")[0]);
            String epost = txtAvdEpost.getText();
            String telefon = txtAvdTelefon.getText();
            String valdChef = (String) dropDownChef.getSelectedItem();
            int chef = Integer.parseInt(valdChef.split(" - ")[0]);
            String beskrivning = txtAvdBeskrivning.getText();

            if (!Validering.ValideraNamn(namn)) {
                JOptionPane.showMessageDialog(this, "Ogiltigt namn.");
                return;
            }
            if (!Validering.ValideraEpost(epost)) {
                JOptionPane.showMessageDialog(this, "ogiltig e-postadress.");
                return;
            }
            if (!Validering.ValideraTelefon(telefon)) {
                JOptionPane.showMessageDialog(this, "Ogiltigt telefonnummer.");
                return;
            }
            if (!Validering.ValideraAdress(adress)) {
                JOptionPane.showMessageDialog(this, "Ogiltig adress.");
                return;
            }
            AvdelningSQL avdelningSQL = new AvdelningSQL(idb);
            avdelningSQL.redigeraAvdelning(avdid, namn, beskrivning, adress, epost, telefon, stad, chef);

            JOptionPane.showMessageDialog(this, "Avdelningen har uppdaterats.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Redigering misslyckades: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSparaAndringarActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // en enkel tillbakaknapp.
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //  java.awt.EventQueue.invokeLater(() -> new RedigeraAvdelning().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAndringar;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> dropDownChef;
    private javax.swing.JComboBox<String> dropDownStad;
    private javax.swing.JLabel lblAvdAdress;
    private javax.swing.JLabel lblAvdBeskrivning;
    private javax.swing.JLabel lblAvdChef;
    private javax.swing.JLabel lblAvdEpost;
    private javax.swing.JLabel lblAvdNamn;
    private javax.swing.JLabel lblAvdStad;
    private javax.swing.JLabel lblAvdTelefon;
    private javax.swing.JLabel lblAvdid;
    private javax.swing.JLabel lblRedigeraAvdelning;
    private javax.swing.JTextField txtAvdAdress;
    private javax.swing.JTextField txtAvdBeskrivning;
    private javax.swing.JTextField txtAvdEpost;
    private javax.swing.JTextField txtAvdNamn;
    private javax.swing.JTextField txtAvdTelefon;
    private javax.swing.JTextField txtAvdid;
    // End of variables declaration//GEN-END:variables
}
