/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 * Gör det möjligt för adminer att redigera befintliga avdelningar. 
 */
public class RedigeraAvdelning extends javax.swing.JFrame {
        private InfDB idb;
        private int avdid;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RedigeraAvdelning.class.getName());

    /**
     * Creates new form RedigeraAvdelning
     */
    public RedigeraAvdelning(InfDB idb, int avdid) {
        this.idb = idb;
        this.avdid = avdid;
        initComponents();
        fyllFalt();
    }
    
    private void fyllFalt() {
        try {
            AvdelningSQL avdSQL = new AvdelningSQL(idb);
            Avdelning avd = avdSQL.hamtaAvdelningMedId(avdid);
            
            txtAvdid.setText(String.valueOf(avd.getAvdid()));
            txtAvdNamn.setText(avd.getNamn());
            txtAvdAdress.setText(avd.getAdress());
            txtAvdStad.setText(String.valueOf(avd.getStad()));
            txtAvdEpost.setText(avd.getEpost());
            txtAvdTelefon.setText(avd.getTelefon());
            txtAvdChef.setText(String.valueOf(avd.getChef()));
            txtAvdBeskrivning.setText(avd.getBeskrivning());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRedigeraAvdelning = new javax.swing.JLabel();
        lblAvdid = new javax.swing.JLabel();
        lblAvdNamn = new javax.swing.JLabel();
        lblAvdAdress = new javax.swing.JLabel();
        lblAvdStad = new javax.swing.JLabel();
        lblAvdEpost = new javax.swing.JLabel();
        lblAvdTelefon = new javax.swing.JLabel();
        lblAvdChef = new javax.swing.JLabel();
        lblAvdBeskrivning = new javax.swing.JLabel();
        txtAvdid = new javax.swing.JTextField();
        txtAvdNamn = new javax.swing.JTextField();
        txtAvdAdress = new javax.swing.JTextField();
        txtAvdStad = new javax.swing.JTextField();
        txtAvdEpost = new javax.swing.JTextField();
        txtAvdTelefon = new javax.swing.JTextField();
        txtAvdChef = new javax.swing.JTextField();
        txtAvdBeskrivning = new javax.swing.JTextField();
        btnSparaAndringar = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRedigeraAvdelning.setText("Redigera avdelning:");

        lblAvdid.setText("Avdid:");

        lblAvdNamn.setText("Namn:");

        lblAvdAdress.setText("Adress:");

        lblAvdStad.setText("Stad:");

        lblAvdEpost.setText("Epost:");

        lblAvdTelefon.setText("Telefon:");

        lblAvdChef.setText("Chef:");

        lblAvdBeskrivning.setText("Beskrivning:");

        btnSparaAndringar.setText("Spara ändringar");
        btnSparaAndringar.addActionListener(this::btnSparaAndringarActionPerformed);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAvdid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRedigeraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSparaAndringar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRedigeraAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdid)
                    .addComponent(txtAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdNamn)
                    .addComponent(txtAvdNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdAdress)
                    .addComponent(txtAvdAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdStad)
                    .addComponent(txtAvdStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdEpost)
                    .addComponent(txtAvdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdTelefon)
                    .addComponent(txtAvdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdChef)
                    .addComponent(txtAvdChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdBeskrivning)
                    .addComponent(txtAvdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSparaAndringar)
                    .addComponent(btnTillbaka))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaAndringarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaAndringarActionPerformed
        // Sparar admins ändringar, validerar namn, epost, telefonnummer och adress. 
        try {
            int avdid = Integer.parseInt(txtAvdid.getText());
            String namn = txtAvdNamn.getText();
            String adress = txtAvdAdress.getText();
            int stad = Integer.parseInt(txtAvdStad.getText());
            String epost = txtAvdEpost.getText();
            String telefon = txtAvdTelefon.getText();
            int chef = Integer.parseInt(txtAvdChef.getText());
            String beskrivning = txtAvdBeskrivning.getText();
            
          if (!Validering.ValideraNamn(namn)) {
              JOptionPane.showMessageDialog(this, "Ogiltigt namn.");
              return;
          }
          if (!Validering.ValideraEpost(epost)) {
              JOptionPane.showMessageDialog(this, "ogiltig e-postadress.");
              return;
          }
          if (!Validering.ValideraTelefon(telefon)) {
              JOptionPane.showMessageDialog(this, "Ogiltigt telefonnummer.");
              return;
          }
          if (!Validering.ValideraAdress(adress)) {
              JOptionPane.showMessageDialog(this, "Ogiltig adress.");
              return;
          }
            AvdelningSQL avdSQL = new AvdelningSQL(idb);
            avdSQL.redigeraAvdelning(avdid, namn, beskrivning, adress, epost, telefon, stad, chef);
            
            JOptionPane.showMessageDialog(this, "Avdelningen har uppdaterats.");
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Redigering misslyckades: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSparaAndringarActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // en enkel tillbakaknapp.
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(() -> new RedigeraAvdelning().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAndringar;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblAvdAdress;
    private javax.swing.JLabel lblAvdBeskrivning;
    private javax.swing.JLabel lblAvdChef;
    private javax.swing.JLabel lblAvdEpost;
    private javax.swing.JLabel lblAvdNamn;
    private javax.swing.JLabel lblAvdStad;
    private javax.swing.JLabel lblAvdTelefon;
    private javax.swing.JLabel lblAvdid;
    private javax.swing.JLabel lblRedigeraAvdelning;
    private javax.swing.JTextField txtAvdAdress;
    private javax.swing.JTextField txtAvdBeskrivning;
    private javax.swing.JTextField txtAvdChef;
    private javax.swing.JTextField txtAvdEpost;
    private javax.swing.JTextField txtAvdNamn;
    private javax.swing.JTextField txtAvdStad;
    private javax.swing.JTextField txtAvdTelefon;
    private javax.swing.JTextField txtAvdid;
    // End of variables declaration//GEN-END:variables
}
